name: storage_info
description: Get storage info on Android and iOS
version: 0.1.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.storage_info
        pluginClass: StorageInfoPlugin
      ios:
        pluginClass: StorageInfoPlugin
